# Generated by Django 5.1.15 on 2026-01-28 15:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Usuari Legacy",
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                ("id", models.SmallAutoField(db_column="Id", primary_key=True, serialize=False)),
                ("name", models.CharField(db_column="Name", max_length=50)),
                ("region", models.CharField(blank=True, db_column="Region", max_length=50, null=True)),
                ("area", models.CharField(blank=True, db_column="Area", max_length=50, null=True)),
                (
                    "latitude",
                    models.DecimalField(blank=True, db_column="Latitude", decimal_places=8, max_digits=15, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, db_column="Longitude", decimal_places=8, max_digits=15, null=True),
                ),
                ("code", models.IntegerField(db_column="Code")),
                ("geom", django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
                (
                    "autonomouscommunity",
                    models.CharField(blank=True, db_column="AutonomousCommunity", max_length=50, null=True),
                ),
                ("fishersassociation", models.BooleanField(blank=True, db_column="FishersAssociation", null=True)),
                ("auction", models.BooleanField(blank=True, db_column="Auction", null=True)),
            ],
            options={
                "verbose_name": "Port",
                "db_table": "port",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PortAll",
            fields=[
                ("name", models.CharField(blank=True, db_column="Name", max_length=50, null=True)),
                ("region", models.CharField(blank=True, db_column="Region", max_length=50, null=True)),
                ("area", models.CharField(blank=True, db_column="Area", max_length=50, null=True)),
                (
                    "latitude",
                    models.DecimalField(blank=True, db_column="Latitude", decimal_places=8, max_digits=15, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, db_column="Longitude", decimal_places=8, max_digits=15, null=True),
                ),
                ("code", models.IntegerField(blank=True, db_column="Code", null=True)),
                ("geom", django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=0)),
                (
                    "autonomouscommunity",
                    models.CharField(blank=True, db_column="AutonomousCommunity", max_length=50, null=True),
                ),
                ("id", models.SmallAutoField(db_column="Id", primary_key=True, serialize=False)),
                ("al5", models.CharField(blank=True, db_column="AL5", max_length=5, null=True)),
                ("fishersassociation", models.BooleanField(blank=True, db_column="FishersAssociation", null=True)),
                ("auction", models.BooleanField(blank=True, db_column="Auction", null=True)),
                ("gsa", models.CharField(blank=True, db_column="GSA", null=True)),
                ("country", models.CharField(blank=True, db_column="Country", null=True)),
            ],
            options={
                "verbose_name": "Port All",
                "db_table": "port_all",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                ("id", models.AutoField(db_column="Id", primary_key=True, serialize=False)),
                ("number_3a_code", models.CharField(blank=True, db_column="3A_Code", max_length=3, null=True)),
                ("scientificname", models.CharField(db_column="ScientificName", max_length=37, unique=True)),
                ("catalanname", models.CharField(blank=True, db_column="CatalanName", max_length=30, null=True)),
                ("spanishname", models.CharField(blank=True, db_column="SpanishName", max_length=30, null=True)),
                ("englishname", models.CharField(blank=True, db_column="EnglishName", max_length=30, null=True)),
                ("group", models.CharField(blank=True, db_column="Group", max_length=50, null=True)),
                ("group2", models.CharField(blank=True, db_column="Group2", max_length=50, null=True)),
                ("frenchname", models.CharField(blank=True, db_column="FrenchName", max_length=30, null=True)),
                (
                    "generalitatname",
                    models.CharField(blank=True, db_column="GeneralitatName", max_length=100, null=True),
                ),
                ("class_field", models.CharField(blank=True, db_column="Class", max_length=30, null=True)),
                ("order", models.CharField(blank=True, db_column="Order", max_length=30, null=True)),
                ("family", models.CharField(blank=True, db_column="Family", max_length=30, null=True)),
                ("genus", models.CharField(blank=True, db_column="Genus", max_length=30, null=True)),
                (
                    "a_const",
                    models.DecimalField(blank=True, db_column="A_Const", decimal_places=4, max_digits=12, null=True),
                ),
                (
                    "b_const",
                    models.DecimalField(blank=True, db_column="B_Const", decimal_places=4, max_digits=12, null=True),
                ),
                ("generalitatcode", models.CharField(blank=True, db_column="GeneralitatCode", max_length=3, null=True)),
                ("observations", models.TextField(blank=True, db_column="Observations", null=True)),
                (
                    "minimumsize",
                    models.DecimalField(
                        blank=True, db_column="MinimumSize", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "maximumsize",
                    models.DecimalField(
                        blank=True, db_column="MaximumSize", decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("numberofsizes", models.IntegerField(blank=True, db_column="NumberOfSizes", null=True)),
                ("iswaste", models.BooleanField(blank=True, db_column="IsWaste", null=True)),
                ("wastetype", models.CharField(blank=True, db_column="WasteType", max_length=30, null=True)),
                ("phylum", models.CharField(blank=True, db_column="Phylum", max_length=30, null=True)),
                ("taxonomicgroup", models.CharField(blank=True, db_column="TaxonomicGroup", max_length=30, null=True)),
                ("demersal", models.BooleanField(blank=True, db_column="Demersal", null=True)),
                ("pelagic", models.BooleanField(blank=True, db_column="Pelagic", null=True)),
                ("hardseabed", models.BooleanField(blank=True, db_column="HardSeabed", null=True)),
                ("softseabed", models.BooleanField(blank=True, db_column="SoftSeabed", null=True)),
                ("bothseabed", models.BooleanField(blank=True, db_column="BothSeabed", null=True)),
                ("cartilaginous", models.BooleanField(blank=True, db_column="Cartilaginous", null=True)),
                ("bony", models.BooleanField(blank=True, db_column="Bony", null=True)),
                ("r", models.SmallIntegerField(blank=True, db_column="R", null=True)),
                ("g", models.SmallIntegerField(blank=True, db_column="G", null=True)),
                ("b", models.SmallIntegerField(blank=True, db_column="B", null=True)),
                ("mcrs", models.DecimalField(blank=True, db_column="MCRS", decimal_places=2, max_digits=12, null=True)),
                ("l50", models.DecimalField(blank=True, db_column="L50", decimal_places=2, max_digits=12, null=True)),
                (
                    "l50female",
                    models.DecimalField(blank=True, db_column="L50Female", decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "l50male",
                    models.DecimalField(blank=True, db_column="L50Male", decimal_places=2, max_digits=12, null=True),
                ),
                ("aphiaid", models.IntegerField(blank=True, db_column="AphiaId", null=True)),
                ("projectid", models.IntegerField(blank=True, db_column="ProjectId", null=True)),
                ("codi_medits", models.TextField(blank=True, null=True)),
                ("categoria_medits", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Espècie",
                "db_table": "species",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VcpeAutoDownload",
            fields=[
                ("vesselcode", models.CharField(blank=True, db_column="VesselCode", max_length=12, null=True)),
                ("vesselname", models.CharField(blank=True, db_column="VesselName", max_length=50, null=True)),
                ("vesseltype", models.CharField(blank=True, db_column="VesselType", max_length=30, null=True)),
                ("salenumber", models.CharField(blank=True, db_column="SaleNumber", max_length=30, null=True)),
                ("lot", models.CharField(blank=True, db_column="Lot", max_length=30, null=True)),
                ("calibre", models.CharField(blank=True, db_column="Calibre", max_length=40, null=True)),
                ("size", models.CharField(blank=True, db_column="Size", max_length=20, null=True)),
                ("doctype", models.CharField(blank=True, db_column="DocType", max_length=10, null=True)),
                ("speciecode", models.CharField(blank=True, db_column="SpecieCode", max_length=3, null=True)),
                ("speciename", models.CharField(blank=True, db_column="SpecieName", max_length=30, null=True)),
                ("portname", models.CharField(blank=True, db_column="PortName", max_length=50, null=True)),
                ("date", models.DateField(blank=True, db_column="Date", null=True)),
                ("porttype", models.CharField(blank=True, db_column="PortType", max_length=40, null=True)),
                ("freshness", models.CharField(blank=True, db_column="Freshness", max_length=20, null=True)),
                ("presentation", models.CharField(blank=True, db_column="Presentation", max_length=50, null=True)),
                ("conservation", models.CharField(blank=True, db_column="Conservation", max_length=20, null=True)),
                ("fishingartcode", models.CharField(blank=True, db_column="FishingArtCode", max_length=10, null=True)),
                ("fishingartname", models.CharField(blank=True, db_column="FishingArtName", max_length=100, null=True)),
                (
                    "vesselownercode",
                    models.CharField(blank=True, db_column="VesselOwnerCode", max_length=50, null=True),
                ),
                (
                    "otherfishingarts",
                    models.CharField(blank=True, db_column="OtherFishingArts", max_length=30, null=True),
                ),
                (
                    "weight",
                    models.DecimalField(blank=True, db_column="Weight", decimal_places=3, max_digits=20, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(blank=True, db_column="Amount", decimal_places=4, max_digits=20, null=True),
                ),
                ("id", models.BigAutoField(db_column="Id", primary_key=True, serialize=False)),
                ("vesselid", models.IntegerField(blank=True, db_column="VesselId", null=True)),
                ("specieid", models.IntegerField(blank=True, db_column="SpecieId", null=True)),
                ("baseportcode", models.IntegerField(blank=True, db_column="BasePortCode", null=True)),
                ("baseportname", models.CharField(blank=True, db_column="BasePortName", max_length=50, null=True)),
                ("metiercat", models.CharField(blank=True, db_column="MetierCAT", max_length=30, null=True)),
                ("metierdcf", models.CharField(blank=True, db_column="MetierDCF", max_length=10, null=True)),
                ("trackcode", models.CharField(blank=True, db_column="TrackCode", null=True)),
            ],
            options={
                "verbose_name": "VCPE Auto Download",
                "db_table": "vcpe_auto_download",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vessel",
            fields=[
                ("code", models.CharField(blank=True, db_column="Code", max_length=12, null=True)),
                ("eventcode", models.CharField(blank=True, db_column="EventCode", max_length=3, null=True)),
                ("eventstartdate", models.DateField(blank=True, db_column="EventStartDate", null=True)),
                ("eventenddate", models.DateField(blank=True, db_column="EventEndDate", null=True)),
                ("licenceind", models.BooleanField(blank=True, db_column="LicenceInd", null=True)),
                (
                    "registrationnum",
                    models.CharField(blank=True, db_column="RegistrationNum", max_length=15, null=True),
                ),
                ("name", models.CharField(blank=True, db_column="Name", max_length=50, null=True)),
                ("baseportcode", models.IntegerField(blank=True, db_column="BasePortCode", null=True)),
                ("baseportname", models.CharField(blank=True, db_column="BasePortName", max_length=30, null=True)),
                ("ircs", models.CharField(blank=True, db_column="IRCS", max_length=10, null=True)),
                ("vms", models.BooleanField(blank=True, db_column="VMS", null=True)),
                ("gearmaincode", models.CharField(blank=True, db_column="GearMainCode", max_length=3, null=True)),
                ("gearseccode", models.CharField(blank=True, db_column="GearSecCode", max_length=3, null=True)),
                (
                    "loa_m",
                    models.DecimalField(blank=True, db_column="LOA_m", decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "lbp_m",
                    models.DecimalField(blank=True, db_column="LBP_m", decimal_places=2, max_digits=10, null=True),
                ),
                ("gt", models.DecimalField(blank=True, db_column="GT", decimal_places=2, max_digits=10, null=True)),
                ("trb", models.DecimalField(blank=True, db_column="TRB", decimal_places=2, max_digits=10, null=True)),
                (
                    "powermain_kw",
                    models.DecimalField(
                        blank=True, db_column="PowerMain_kW", decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "poweraux_kw",
                    models.DecimalField(
                        blank=True, db_column="PowerAux_kW", decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("hullmaterial", models.CharField(blank=True, db_column="HullMaterial", max_length=20, null=True)),
                ("servicestartingdate", models.DateField(blank=True, db_column="ServiceStartingDate", null=True)),
                ("ais", models.BooleanField(blank=True, db_column="AIS", null=True)),
                ("id", models.AutoField(db_column="Id", primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Vaixell",
                "db_table": "vessel",
                "managed": False,
            },
        ),
    ]
