# Generated by Django 5.1.15 on 2026-02-02 16:00

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Envio",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "num_envio",
                    models.CharField(db_index=True, help_text="Número únic d'enviament", max_length=50, unique=True),
                ),
                ("fecha_recepcion", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("ip_origen", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "procesado_en_db",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Indica si la BBDD ha processat aquest enviament"
                    ),
                ),
                ("fecha_procesado_en_db", models.DateTimeField(blank=True, null=True)),
                (
                    "error_procesado",
                    models.TextField(blank=True, help_text="Error retornat pel procés de la BBDD", null=True),
                ),
                (
                    "usuario_envio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="envios", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Enviament (Staging)",
                "verbose_name_plural": "Enviaments (Staging)",
                "db_table": "envio_staging",
                "ordering": ["-fecha_recepcion"],
            },
        ),
        migrations.CreateModel(
            name="RawSalesNote",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("raw_data", models.JSONField(help_text="El payload JSON complet de la nota de venda")),
                (
                    "envio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="raw_notes", to="sales_notes.envio"
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Venda Crua (Staging)",
                "verbose_name_plural": "Notes de Venda Crues (Staging)",
                "db_table": "raw_sales_note",
                "ordering": ["-created_at"],
            },
        ),
    ]
