# Generated by Django 5.1.2 on 2025-10-22 12:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadProductiva",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "metodo_produccion",
                    models.IntegerField(
                        choices=[
                            (1, "Pesca extractiva marina"),
                            (2, "Aqüicultura marina"),
                            (3, "Pesca extractiva aigües interiors"),
                            (4, "Aqüicultura aigües interiors"),
                        ],
                        db_index=True,
                    ),
                ),
                (
                    "tipo_unidad",
                    models.CharField(
                        choices=[("BUQUE", "Vaixell"), ("GRANJA", "Granja"), ("PERSONA", "Persona Física/Jurídica")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unitat productiva",
                "verbose_name_plural": "Unitats productives",
                "db_table": "unidad_productiva",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EstablecimientoVenta",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "num_identificacion_establec",
                    models.CharField(db_index=True, help_text="Número d'identificació de l'establiment", max_length=50),
                ),
            ],
            options={
                "verbose_name": "Establiment de venda",
                "verbose_name_plural": "Establiments de venda",
                "db_table": "establecimiento_venta",
                "ordering": ["num_identificacion_establec"],
            },
        ),
        migrations.CreateModel(
            name="Buque",
            fields=[
                (
                    "unidad_productiva",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="buque",
                        serialize=False,
                        to="sales_notes.unidadproductiva",
                    ),
                ),
                (
                    "codigo_buque",
                    models.CharField(db_index=True, help_text="Codi del vaixell (matrícula)", max_length=12),
                ),
                (
                    "puerto_al5",
                    models.CharField(
                        blank=True,
                        help_text="Codi del port en format AL5",
                        max_length=5,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Format invàlid. Ha de ser 2 lletres + 3 alfanumèrics (ex: ESBAR)",
                                regex="^[A-Za-z]{2}[A-Za-z0-9]{3}$",
                            )
                        ],
                    ),
                ),
                ("armador", models.CharField(blank=True, max_length=100)),
                ("capitan", models.CharField(blank=True, max_length=60)),
                ("fecha_regreso_puerto", models.DateTimeField(help_text="Data i hora de retorn al port")),
                ("cod_marea", models.CharField(blank=True, help_text="Codi de marea", max_length=50)),
            ],
            options={
                "verbose_name": "Vaixell",
                "verbose_name_plural": "Vaixells",
                "db_table": "buque",
            },
        ),
        migrations.CreateModel(
            name="Granja",
            fields=[
                (
                    "unidad_productiva",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="granja",
                        serialize=False,
                        to="sales_notes.unidadproductiva",
                    ),
                ),
                ("codigo_rega", models.CharField(db_index=True, help_text="Codi REGA de la granja", max_length=14)),
                ("lugar_descarga", models.CharField(blank=True, help_text="Lloc de descàrrega", max_length=250)),
                ("fecha_produccion", models.DateTimeField(help_text="Data de producció")),
            ],
            options={
                "verbose_name": "Granja",
                "verbose_name_plural": "Granges",
                "db_table": "granja",
            },
        ),
        migrations.CreateModel(
            name="PersonaFisicaJuridica",
            fields=[
                (
                    "unidad_productiva",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="persona",
                        serialize=False,
                        to="sales_notes.unidadproductiva",
                    ),
                ),
                ("nif_persona", models.CharField(db_index=True, help_text="NIF/NIE/CIF de la persona", max_length=17)),
                ("lugar_descarga", models.CharField(blank=True, help_text="Lloc de descàrrega", max_length=250)),
                ("fecha_descarga", models.DateTimeField(help_text="Data de descàrrega")),
            ],
            options={
                "verbose_name": "Persona física/jurídica",
                "verbose_name_plural": "Persones físiques/jurídiques",
                "db_table": "persona_fisica_juridica",
            },
        ),
        migrations.CreateModel(
            name="Envio",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "num_envio",
                    models.CharField(db_index=True, help_text="Número únic d'enviament", max_length=50, unique=True),
                ),
                (
                    "tipo_respuesta",
                    models.IntegerField(
                        choices=[(1, "Completa"), (2, "Media"), (3, "Reducida")],
                        default=1,
                        help_text="Tipus de resposta esperada del sistema",
                    ),
                ),
                ("fecha_recepcion", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("procesado", models.BooleanField(db_index=True, default=False)),
                ("fecha_procesado", models.DateTimeField(blank=True, null=True)),
                ("validado", models.BooleanField(default=False)),
                ("errores", models.JSONField(blank=True, default=list)),
                ("ip_origen", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "usuario_envio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="envios", to="authentication.apiuser"
                    ),
                ),
            ],
            options={
                "verbose_name": "Enviament",
                "verbose_name_plural": "Enviaments",
                "db_table": "envio",
                "ordering": ["-fecha_recepcion"],
            },
        ),
        migrations.CreateModel(
            name="Especie",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "num_doc_venta",
                    models.CharField(db_index=True, help_text="Número del document de venda", max_length=21),
                ),
                (
                    "especie_al3",
                    models.CharField(
                        db_index=True,
                        help_text="Codi FAO de l'espècie (3 lletres)",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Codi AL3 invàlid (ha de ser 3 lletres)", regex="^[A-Za-z]{3}$"
                            )
                        ],
                    ),
                ),
                ("zona", models.CharField(blank=True, max_length=50)),
                ("zona_geografica", models.CharField(blank=True, max_length=50)),
                ("ccaa", models.IntegerField(blank=True, help_text="Codi Comunitat Autònoma", null=True)),
                (
                    "pais_al3",
                    models.CharField(
                        blank=True,
                        help_text="Codi ISO-3 del país",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Codi AL3 invàlid (ha de ser 3 lletres)", regex="^[A-Za-z]{3}$"
                            )
                        ],
                    ),
                ),
                (
                    "masa_agua",
                    models.CharField(blank=True, help_text="Massa d'aigua on es va capturar", max_length=100),
                ),
                (
                    "arte_al3",
                    models.CharField(blank=True, db_index=True, help_text="Codi d'art de pesca (FAO)", max_length=3),
                ),
                (
                    "otro_arte",
                    models.CharField(
                        blank=True, help_text="Descripció d'altres arts no estandarditzats", max_length=100
                    ),
                ),
                (
                    "cod_especie_conservacion",
                    models.CharField(blank=True, help_text="Codi estat de conservació", max_length=3),
                ),
                (
                    "cod_especie_presentacion",
                    models.CharField(blank=True, help_text="Codi presentació del producte", max_length=5),
                ),
                ("presentacion_oth", models.CharField(blank=True, help_text="Altres presentacions", max_length=50)),
                ("id_presentacion_oth", models.IntegerField(blank=True, null=True)),
                ("cod_especie_frescura", models.CharField(blank=True, help_text="Codi frescura", max_length=2)),
                ("cod_especie_calibre", models.CharField(blank=True, help_text="Codi calibre", max_length=15)),
                ("fecha_venta", models.DateTimeField(db_index=True, help_text="Data i hora de venda")),
                ("lote", models.CharField(blank=True, help_text="Número de lot", max_length=50)),
                (
                    "cod_contrato_alim",
                    models.CharField(blank=True, help_text="Codi contracte alimentari", max_length=50),
                ),
                (
                    "num_doc_transporte",
                    models.CharField(blank=True, help_text="Número document de transport", max_length=50),
                ),
                (
                    "num_declaracion_recog",
                    models.CharField(blank=True, help_text="Número declaració recollida", max_length=21),
                ),
                ("certificado_de_origen", models.BooleanField(default=False, help_text="Té certificat d'origen")),
                (
                    "tipo_cif_nif_vendedor",
                    models.IntegerField(
                        choices=[(1, "NIF"), (2, "NIE"), (3, "Passaport"), (5, "Altres documents")],
                        help_text="Tipus document identificació venedor",
                    ),
                ),
                ("nif_vendedor", models.CharField(db_index=True, help_text="NIF/CIF del venedor", max_length=17)),
                ("nombre_vendedor", models.CharField(help_text="Nom del venedor", max_length=100)),
                ("direccion_vendedor", models.CharField(blank=True, help_text="Direcció del venedor", max_length=100)),
                ("nif_comprador", models.CharField(db_index=True, help_text="NIF/CIF del comprador", max_length=17)),
                (
                    "id_tipo_nif_cif_comprador",
                    models.IntegerField(
                        choices=[(1, "NIF"), (2, "NIE"), (3, "Passaport"), (5, "Altres documents")],
                        help_text="Tipus document identificació comprador",
                    ),
                ),
                (
                    "pais_comprador",
                    models.CharField(
                        blank=True,
                        help_text="Codi ISO-3 país del comprador",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Codi país invàlid (ISO-3, 3 lletres)", regex="^[A-Za-z]{3}$"
                            )
                        ],
                    ),
                ),
                ("nombre_comprador", models.CharField(help_text="Nom del comprador", max_length=100)),
                (
                    "direccion_comprador",
                    models.CharField(blank=True, help_text="Direcció del comprador", max_length=100),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Preu total",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "cod_moneda",
                    models.CharField(
                        default="EUR",
                        help_text="Codi ISO-4217 moneda",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Codi moneda invàlid (ISO-4217, 3 lletres)", regex="^[A-Za-z]{3}$"
                            )
                        ],
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Quantitat en kg",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                    ),
                ),
                (
                    "num_ejemplares",
                    models.IntegerField(
                        blank=True,
                        help_text="Nombre d'exemplars",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "num_cajas",
                    models.IntegerField(
                        blank=True,
                        help_text="Nombre de caixes",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("es_talla_reglamentaria", models.BooleanField(default=True, help_text="És talla reglamentària")),
                (
                    "tipo_retirada",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "No s'ha retirat"),
                            (2, "Retirada per talla"),
                            (3, "Retirada per quota"),
                            (4, "Retirada sense preu"),
                            (5, "Retirada altre"),
                            (6, "Desembarcament per sota mínims"),
                        ],
                        help_text="Tipus de retirada",
                        null=True,
                    ),
                ),
                (
                    "cod_destino_retirado",
                    models.CharField(blank=True, help_text="Codi destí del producte retirat", max_length=50),
                ),
                (
                    "lugar_almacenamiento",
                    models.CharField(blank=True, help_text="Lloc d'emmagatzematge", max_length=100),
                ),
                ("observaciones", models.TextField(blank=True, help_text="Observacions addicionals")),
                (
                    "num_acta_inspeccion",
                    models.CharField(blank=True, help_text="Número d'acta d'inspecció", max_length=20),
                ),
                (
                    "unidad_productiva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="especies",
                        to="sales_notes.unidadproductiva",
                    ),
                ),
            ],
            options={
                "verbose_name": "Espècie",
                "verbose_name_plural": "Espècies",
                "db_table": "especie",
                "ordering": ["-fecha_venta"],
            },
        ),
        migrations.AddField(
            model_name="unidadproductiva",
            name="establecimiento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unidades_productivas",
                to="sales_notes.establecimientoventa",
            ),
        ),
        migrations.AddField(
            model_name="establecimientoventa",
            name="envio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="establecimientos", to="sales_notes.envio"
            ),
        ),
        migrations.CreateModel(
            name="FechaCaptura",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("fecha_captura_ini", models.DateTimeField(help_text="Data i hora inici captura")),
                (
                    "fecha_captura_fin",
                    models.DateTimeField(blank=True, help_text="Data i hora fi captura (opcional)", null=True),
                ),
                (
                    "especie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fechas_captura",
                        to="sales_notes.especie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data de captura",
                "verbose_name_plural": "Dates de captura",
                "db_table": "fecha_captura",
                "ordering": ["fecha_captura_ini"],
            },
        ),
        migrations.AddIndex(
            model_name="envio",
            index=models.Index(fields=["num_envio", "fecha_recepcion"], name="envio_num_env_1bb15e_idx"),
        ),
        migrations.AddIndex(
            model_name="envio",
            index=models.Index(fields=["procesado", "validado"], name="envio_procesa_6808ba_idx"),
        ),
        migrations.AddIndex(
            model_name="especie",
            index=models.Index(fields=["especie_al3", "fecha_venta"], name="especie_especie_7b6b90_idx"),
        ),
        migrations.AddIndex(
            model_name="especie",
            index=models.Index(fields=["arte_al3", "zona"], name="especie_arte_al_ca1645_idx"),
        ),
        migrations.AddIndex(
            model_name="especie",
            index=models.Index(fields=["nif_vendedor", "fecha_venta"], name="especie_nif_ven_bace9e_idx"),
        ),
        migrations.AddIndex(
            model_name="especie",
            index=models.Index(fields=["nif_comprador", "fecha_venta"], name="especie_nif_com_78b55a_idx"),
        ),
        migrations.AddIndex(
            model_name="unidadproductiva",
            index=models.Index(fields=["tipo_unidad", "metodo_produccion"], name="unidad_prod_tipo_un_f35eef_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="establecimientoventa",
            unique_together={("envio", "num_identificacion_establec")},
        ),
        migrations.AddIndex(
            model_name="fechacaptura",
            index=models.Index(
                fields=["fecha_captura_ini", "fecha_captura_fin"], name="fecha_captu_fecha_c_77b9cf_idx"
            ),
        ),
    ]
