# Generated by Django 5.1.2 on 2025-10-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_notes", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="buque",
            constraint=models.CheckConstraint(
                condition=models.Q(("unidad_productiva__metodo_produccion__in", [1, 4])),
                name="buque_metodo_produccion_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="granja",
            constraint=models.CheckConstraint(
                condition=models.Q(("unidad_productiva__metodo_produccion", 2)), name="granja_metodo_produccion_valido"
            ),
        ),
        migrations.AddConstraint(
            model_name="personafisicajuridica",
            constraint=models.CheckConstraint(
                condition=models.Q(("unidad_productiva__metodo_produccion__in", [1, 3, 4])),
                name="persona_metodo_produccion_valido",
            ),
        ),
    ]
