# Generated by Django 5.1.2 on 2025-11-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buque",
            name="armador",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="buque",
            name="capitan",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="buque",
            name="cod_marea",
            field=models.CharField(blank=True, help_text="Codi de marea", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="buque",
            name="codigo_buque",
            field=models.CharField(db_index=True, help_text="Codi del vaixell (matrícula)", max_length=20),
        ),
    ]
