# Generated by Django 5.1.13 on 2025-11-27 14:14

from decimal import Decimal

import django.core.validators
from django.db import migrations

import sales_notes.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ("sales_notes", "0002_alter_buque_armador_alter_buque_capitan_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="especie",
            name="especie_nif_ven_bace9e_idx",
        ),
        migrations.RemoveIndex(
            model_name="especie",
            name="especie_nif_com_78b55a_idx",
        ),
        migrations.AlterField(
            model_name="especie",
            name="cantidad",
            field=sales_notes.encrypted_fields.EncryptedDecimalField(
                help_text="Quantitat en kg (xifrat)",
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AlterField(
            model_name="especie",
            name="direccion_comprador",
            field=sales_notes.encrypted_fields.EncryptedCharField(
                blank=True, help_text="Direcció del comprador (xifrat)"
            ),
        ),
        migrations.AlterField(
            model_name="especie",
            name="direccion_vendedor",
            field=sales_notes.encrypted_fields.EncryptedCharField(
                blank=True, help_text="Direcció del venedor (xifrat)"
            ),
        ),
        migrations.AlterField(
            model_name="especie",
            name="nif_comprador",
            field=sales_notes.encrypted_fields.EncryptedCharField(help_text="NIF/CIF del comprador (xifrat)"),
        ),
        migrations.AlterField(
            model_name="especie",
            name="nif_vendedor",
            field=sales_notes.encrypted_fields.EncryptedCharField(help_text="NIF/CIF del venedor (xifrat)"),
        ),
        migrations.AlterField(
            model_name="especie",
            name="precio",
            field=sales_notes.encrypted_fields.EncryptedDecimalField(
                help_text="Preu total (xifrat)", validators=[django.core.validators.MinValueValidator(Decimal("0.00"))]
            ),
        ),
    ]
