# Generated by Django 5.1.15 on 2026-06-16 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_notes", "0004_update_trigger_and_add_envio_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="envio",
            name="usuario_envio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="envios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
