# Generated by Django 5.1.2 on 2025-10-22 11:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIAccessLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("endpoint", models.CharField(max_length=500)),
                ("method", models.CharField(max_length=10)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("request_id", models.CharField(db_index=True, max_length=50)),
                ("status_code", models.IntegerField()),
                ("response_time_ms", models.IntegerField(help_text="Temps de resposta en ms")),
                (
                    "request_body_hash",
                    models.CharField(blank=True, help_text="Hash SHA256 del body (per privacitat)", max_length=64),
                ),
                ("error_message", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'accés API",
                "verbose_name_plural": "Logs d'accés API",
                "db_table": "api_access_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["user", "timestamp"], name="api_access__user_id_d9d614_idx"),
                    models.Index(fields=["ip_address", "timestamp"], name="api_access__ip_addr_bd9b0b_idx"),
                    models.Index(fields=["status_code", "timestamp"], name="api_access__status__edc88e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="APIUser",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "organizacion",
                    models.CharField(
                        help_text="Nom de l'organització (ex: Confraria de pescadors, llotja)", max_length=200
                    ),
                ),
                ("cif_organizacion", models.CharField(help_text="CIF de l'organització", max_length=20, unique=True)),
                (
                    "telefono",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Número de telèfon invàlid", regex="^\\+?1?\\d{9,15}$"
                            )
                        ],
                    ),
                ),
                (
                    "is_api_active",
                    models.BooleanField(default=True, help_text="Indica si l'usuari pot accedir a l'API"),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="API Key per autenticació addicional (opcional)",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("max_requests_per_day", models.IntegerField(default=10000, help_text="Màxim de peticions per dia")),
                ("max_requests_per_hour", models.IntegerField(default=1000, help_text="Màxim de peticions per hora")),
                (
                    "allowed_ips",
                    models.JSONField(blank=True, default=list, help_text="Llista d'IPs permeses (buit = totes)"),
                ),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("failed_login_attempts", models.IntegerField(default=0)),
                ("account_locked_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Usuari del sistema (auth_user de public)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuari API",
                "verbose_name_plural": "Usuaris API",
                "db_table": "api_user",
                "indexes": [
                    models.Index(fields=["user"], name="api_user_user_id_84e11c_idx"),
                    models.Index(fields=["cif_organizacion"], name="api_user_cif_org_f8feeb_idx"),
                    models.Index(fields=["is_api_active"], name="api_user_is_api__635139_idx"),
                ],
            },
        ),
    ]
