# Generated by Django 5.1.2 on 2025-11-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="apiuser",
            name="api_user_cif_org_f8feeb_idx",
        ),
        migrations.RenameField(
            model_name="apiuser",
            old_name="cif_organizacion",
            new_name="cif_organization",
        ),
        migrations.RenameField(
            model_name="apiuser",
            old_name="organizacion",
            new_name="organization",
        ),
        migrations.AddField(
            model_name="apiuser",
            name="is_locked",
            field=models.BooleanField(default=False, help_text="Indica si el compte està bloquejat per seguretat"),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="last_failed_login",
            field=models.DateTimeField(blank=True, help_text="Data de l'últim intent de login fallit", null=True),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="lock_reason",
            field=models.CharField(blank=True, help_text="Raó del bloqueig del compte", max_length=255),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="locked_until",
            field=models.DateTimeField(blank=True, help_text="Data fins quan està bloquejat el compte", null=True),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="must_change_password",
            field=models.BooleanField(
                default=False, help_text="Indica si l'usuari ha de canviar la contrasenya al proper login"
            ),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="password_changed_at",
            field=models.DateTimeField(blank=True, help_text="Data de l'últim canvi de contrasenya", null=True),
        ),
        migrations.AddIndex(
            model_name="apiuser",
            index=models.Index(fields=["cif_organization"], name="api_user_cif_org_0dffaf_idx"),
        ),
    ]
