# Generated by Django 5.1.15 on 2026-06-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authenticationtoken",
            name="revoked_by",
        ),
        migrations.RemoveField(
            model_name="authenticationtoken",
            name="user",
        ),
        migrations.DeleteModel(
            name="AuthenticationAuditLog",
        ),
        migrations.DeleteModel(
            name="AuthenticationToken",
        ),
    ]
