# Generated by Django 5.1.2 on 2025-11-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_apiuser_api_user_cif_org_f8feeb_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiuser",
            name="cif_organization",
            field=models.CharField(help_text="CIF de l'organització", max_length=20),
        ),
    ]
