# Generated by Django 5.1.13 on 2026-01-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0004_alter_apiuser_groups_alter_apiuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="""The groups this user belongs to. A user will get all
                permissions granted to each of their groups.""",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="apiuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="""Designates whether this user should be treated as active.
                Unselect this instead of deleting accounts.""",
                verbose_name="active",
            ),
        ),
    ]
