# Generated by Django 5.1.2 on 2025-10-21 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audit", "0001_initial"),
        ("sales_notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="datavalidationerror",
            name="envio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="validation_errors", to="sales_notes.envio"
            ),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_security_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="securityevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="security_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action", "timestamp"], name="audit_log_action_09d227_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user", "timestamp"], name="audit_log_user_id_835db7_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["severity", "timestamp"], name="audit_log_severit_917ad4_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["ip_address", "timestamp"], name="audit_log_ip_addr_f3d5f9_idx"),
        ),
        migrations.AddIndex(
            model_name="datavalidationerror",
            index=models.Index(fields=["field_name", "error_type"], name="data_valida_field_n_1d0294_idx"),
        ),
        migrations.AddIndex(
            model_name="datavalidationerror",
            index=models.Index(fields=["resolved", "timestamp"], name="data_valida_resolve_a34aa9_idx"),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(fields=["event_type", "timestamp"], name="security_ev_event_t_0b896c_idx"),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(fields=["severity", "status"], name="security_ev_severit_a7cdf6_idx"),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(fields=["ip_address", "timestamp"], name="security_ev_ip_addr_db6ebc_idx"),
        ),
        migrations.AddIndex(
            model_name="securityevent",
            index=models.Index(fields=["blocked", "timestamp"], name="security_ev_blocked_fccb27_idx"),
        ),
    ]
