# Generated by Django 5.1.15 on 2026-06-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("BRUTE_FORCE", "Intent de força bruta"),
                    ("SQL_INJECTION", "Intent d'injecció SQL"),
                    ("XSS_ATTEMPT", "Intent de XSS"),
                    ("INVALID_TOKEN", "Token invàlid"),
                    ("RATE_LIMIT_EXCEEDED", "Límit de peticions excedit"),
                    ("UNAUTHORIZED_ACCESS", "Accés no autoritzat"),
                    ("RECONNAISSANCE_ATTEMPT", "Intent de reconeixement"),
                    ("SUSPICIOUS_ACTIVITY", "Activitat sospitosa"),
                    ("DATA_BREACH_ATTEMPT", "Intent de filtrament de dades"),
                    ("MALFORMED_REQUEST", "Petició mal formada"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
